/**
 * Option lists for the employer job-posting flow.
 *
 * Values MUST match what the backend stores (see
 * App\Http\Controllers\Employer\JobController::getDropdownOptions and the
 * mobile EmployerController::createJob validation). Labels are display-only.
 */

export interface Option {
  value: string;
  label: string;
}

export const JOB_TYPES: Option[] = [
  { value: "Full Time", label: "Full Time" },
  { value: "Part Time", label: "Part Time" },
  { value: "Contract", label: "Contract" },
  { value: "Temporary", label: "Temporary" },
  { value: "Internship", label: "Internship" },
  { value: "Freelance", label: "Freelance" },
];

export const WORK_ARRANGEMENTS: Option[] = [
  { value: "On Site", label: "On-site" },
  { value: "Remote", label: "Remote" },
  { value: "Hybrid", label: "Hybrid" },
];

export const EXPERIENCE_LEVELS: Option[] = [
  { value: "Entry", label: "Entry Level" },
  { value: "Junior", label: "Junior (1-2 years)" },
  { value: "Mid", label: "Mid Level (3-5 years)" },
  { value: "Senior", label: "Senior (5-8 years)" },
  { value: "Lead", label: "Lead (8+ years)" },
  { value: "Executive", label: "Executive" },
];

export const EDUCATION_LEVELS: Option[] = [
  { value: "high_school", label: "High School" },
  { value: "associate", label: "Associate Degree" },
  { value: "bachelor", label: "Bachelor's Degree" },
  { value: "master", label: "Master's Degree" },
  { value: "doctorate", label: "Doctorate" },
  { value: "other", label: "Other" },
];

export const SALARY_TYPES: Option[] = [
  { value: "hourly", label: "Hourly" },
  { value: "daily", label: "Daily" },
  { value: "weekly", label: "Weekly" },
  { value: "monthly", label: "Monthly" },
  { value: "yearly", label: "Yearly" },
];

export const APPLICATION_METHODS: Option[] = [
  { value: "internal", label: "Through AnyJobs" },
  { value: "external", label: "External URL" },
  { value: "email", label: "Email" },
];

/** Curated set of common currencies (ISO code stored in salary_currency). */
export const CURRENCIES: Option[] = [
  { value: "GBP", label: "GBP £ — British Pound" },
  { value: "USD", label: "USD $ — US Dollar" },
  { value: "EUR", label: "EUR € — Euro" },
  { value: "BDT", label: "BDT ৳ — Bangladeshi Taka" },
  { value: "INR", label: "INR ₹ — Indian Rupee" },
  { value: "CAD", label: "CAD C$ — Canadian Dollar" },
  { value: "AUD", label: "AUD A$ — Australian Dollar" },
  { value: "AED", label: "AED د.إ — UAE Dirham" },
  { value: "SAR", label: "SAR ﷼ — Saudi Riyal" },
  { value: "SGD", label: "SGD S$ — Singapore Dollar" },
  { value: "MYR", label: "MYR RM — Malaysian Ringgit" },
  { value: "PKR", label: "PKR ₨ — Pakistani Rupee" },
  { value: "NPR", label: "NPR रू — Nepalese Rupee" },
  { value: "LKR", label: "LKR ₨ — Sri Lankan Rupee" },
  { value: "JPY", label: "JPY ¥ — Japanese Yen" },
  { value: "CNY", label: "CNY ¥ — Chinese Yuan" },
  { value: "HKD", label: "HKD HK$ — Hong Kong Dollar" },
  { value: "ZAR", label: "ZAR R — South African Rand" },
  { value: "NGN", label: "NGN ₦ — Nigerian Naira" },
  { value: "BRL", label: "BRL R$ — Brazilian Real" },
  { value: "CHF", label: "CHF Fr — Swiss Franc" },
  { value: "SEK", label: "SEK kr — Swedish Krona" },
  { value: "NZD", label: "NZD NZ$ — New Zealand Dollar" },
  { value: "KRW", label: "KRW ₩ — South Korean Won" },
];

/** Full industry list (matches global_industries on the backend). */
export const INDUSTRIES: string[] = [
  "3D Printing & Additive Manufacturing",
  "Accounting & Auditing",
  "Aerospace & Defense",
  "Agriculture",
  "AgriTech",
  "Agro (Plant/Animal/Fisheries)",
  "Alternative & Holistic Medicine",
  "Animation & VFX",
  "Architecture & Planning",
  "Artificial Intelligence",
  "Automotive Manufacturing",
  "Automotive Services",
  "Aviation",
  "Bakery & Confectionery",
  "Bank/Non-Bank Fin. Institution",
  "Banking",
  "Beauty & Personal Care",
  "Biotechnology",
  "Blockchain & Cryptocurrency",
  "BPO & Outsourcing",
  "Cannabis & Hemp",
  "Cement, Glass & Ceramics",
  "Chemicals & Petrochemicals",
  "Childcare & Early Education",
  "Civil Engineering",
  "Clean Technology",
  "Cleaning & Facilities Management",
  "Cloud Computing & SaaS",
  "Computer Hardware Manufacturing",
  "Construction",
  "Consulting",
  "Consumer Goods (FMCG)",
  "Courier & Delivery Services",
  "Coworking & Shared Spaces",
  "Cybersecurity",
  "Dairy & Livestock",
  "Data Analytics & Big Data",
  "Defence & Military",
  "Dental & Oral Health",
  "Design & Creative Services",
  "Digital Media",
  "Domestic & Household Services",
  "Drone Technology",
  "E-commerce",
  "EdTech",
  "Education",
  "Elder Care & Assisted Living",
  "Electric Vehicles",
  "Electronics & Appliance Retail",
  "Electronics Manufacturing",
  "Environmental Services",
  "Esports & Competitive Gaming",
  "Event Management & Conferences",
  "Fashion & Apparel",
  "Finance",
  "Fintech",
  "Fitness & Wellness",
  "Food & Beverage",
  "FoodTech",
  "Forestry & Timber",
  "Freelance & Gig Economy",
  "Funeral & Memorial Services",
  "Furniture & Home Improvement",
  "Gambling & Betting",
  "Gaming",
  "Garments/Textile",
  "Government",
  "GovTech",
  "Healthcare",
  "HealthTech & Telemedicine",
  "Higher Education & Research",
  "Hospitality",
  "HRTech",
  "Human Resources & Staffing",
  "Import/Export & International Trade",
  "Information Technology Services",
  "Insurance",
  "InsurTech",
  "Interior Design",
  "Internet of Things (IoT)",
  "Investment Management",
  "Journalism & Publishing",
  "Judiciary & Law Enforcement",
  "Landscaping & Grounds Maintenance",
  "Laundry & Dry Cleaning",
  "Leather & Footwear",
  "Legal Services",
  "LegalTech",
  "Libraries, Museums & Cultural",
  "Luxury Goods & Jewellery",
  "Management Consulting",
  "Manufacturing",
  "Marketing & Advertising",
  "MarTech (Marketing Technology)",
  "Media & Entertainment",
  "Media/Ad./Event Mgt.",
  "Medical Devices",
  "Mental Health & Counseling",
  "Mining & Metals",
  "Mortgage & Lending",
  "Moving & Relocation",
  "Music & Performing Arts",
  "Nanotechnology",
  "NGO/Development",
  "Non-Profit",
  "Nuclear Energy",
  "Occupational Health & Safety",
  "Oil & Gas",
  "Online Learning & MOOCs",
  "Optical & Eye Care",
  "Organic & Sustainable Farming",
  "Paper & Pulp",
  "Pest Control",
  "Pet Care & Grooming",
  "Pharmaceutical",
  "Pharmaceutical Manufacturing",
  "Pharmacy & Drug Retail",
  "Photography & Videography",
  "Plastics & Rubber",
  "Printing & Packaging",
  "Property Management",
  "PropTech (Property Technology)",
  "Public Health & Epidemiology",
  "Public Relations",
  "Quantum Computing",
  "Railways & Metro",
  "Real Estate",
  "Recycling & Waste Management",
  "Religious & Faith Organizations",
  "Renewable Energy",
  "Research & Development",
  "Restaurants & Food Service",
  "Retail",
  "Ride-Hailing & Mobility",
  "Robotics & Automation",
  "Security & Investigations",
  "Semiconductor & Chip Design",
  "Shipbuilding & Marine Engineering",
  "Shipping & Maritime",
  "Skilled Trades & Crafts",
  "Smart Home & Home Automation",
  "Social Services & Community",
  "Software Development",
  "Solar Energy",
  "Space Technology",
  "Sports & Recreation",
  "Steel, Iron & Metal Works",
  "Supermarkets & Grocery",
  "Supply Chain & Procurement",
  "Survey, Mapping & Geospatial",
  "Tea, Coffee & Plantations",
  "Technology",
  "Telecommunications",
  "Theme Parks & Attractions",
  "Tobacco",
  "Toys, Games & Hobbies",
  "Translation & Interpretation",
  "Transportation & Logistics",
  "Travel & Tourism",
  "Utilities",
  "Venture Capital & Private Equity",
  "Veterinary Services",
  "Virtual Reality & Augmented Reality",
  "Vocational Training & Coaching",
  "Warehousing & Distribution",
  "Water & Sanitation",
  "Wearable Technology",
  "Wholesale Trade & Distribution",
  "Wind Energy",
  "Writing & Content",
];

export const INDUSTRY_OPTIONS: Option[] = INDUSTRIES.map((name) => ({
  value: name,
  label: name,
}));

/**
 * Map a company country (name or ISO code) to a default currency ISO,
 * limited to the currencies offered in CURRENCIES above. Returns null when
 * unknown so callers can keep their existing default.
 */
const COUNTRY_TO_CURRENCY: Record<string, string> = {
  // United Kingdom
  "united kingdom": "GBP", "uk": "GBP", "gb": "GBP", "great britain": "GBP", "england": "GBP",
  // United States
  "united states": "USD", "united states of america": "USD", "usa": "USD", "us": "USD",
  // Eurozone
  germany: "EUR", de: "EUR", france: "EUR", fr: "EUR", spain: "EUR", es: "EUR",
  italy: "EUR", it: "EUR", netherlands: "EUR", nl: "EUR", ireland: "EUR", ie: "EUR",
  portugal: "EUR", pt: "EUR", belgium: "EUR", be: "EUR", austria: "EUR", at: "EUR",
  greece: "EUR", finland: "EUR", "eurozone": "EUR",
  // Rest
  bangladesh: "BDT", bd: "BDT", india: "INR", in: "INR", canada: "CAD", ca: "CAD",
  australia: "AUD", au: "AUD", "united arab emirates": "AED", uae: "AED", ae: "AED",
  "saudi arabia": "SAR", sa: "SAR", singapore: "SGD", sg: "SGD", malaysia: "MYR", my: "MYR",
  pakistan: "PKR", pk: "PKR", nepal: "NPR", np: "NPR", "sri lanka": "LKR", lk: "LKR",
  japan: "JPY", jp: "JPY", china: "CNY", cn: "CNY", "hong kong": "HKD", hk: "HKD",
  "south africa": "ZAR", za: "ZAR", nigeria: "NGN", ng: "NGN", brazil: "BRL", br: "BRL",
  switzerland: "CHF", ch: "CHF", sweden: "SEK", se: "SEK", "new zealand": "NZD", nz: "NZD",
  "south korea": "KRW", "korea": "KRW", kr: "KRW",
};

export function currencyForCountry(country?: string | null): string | null {
  if (!country) return null;
  return COUNTRY_TO_CURRENCY[country.trim().toLowerCase()] ?? null;
}
